import os
# ...existing code...
from sistema_veterinario.static import some_module
# ...existing code...

# Atualize qualquer referência à pasta 'static'
static_path = os.path.join(os.path.dirname(__file__), 'static')
# ...existing code...
